#account模块配置文件
server:
  port: 8050
#添加了整合MyBatis的依赖必须要配置数据库信息
spring:
  datasource:
    username: root
    password: 550098879
    url: jdbc:mysql://localhost:3306/orderingsystem?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml

